### ISSUE TITLE
New exception after upgrade to 2.2.0

### ISSUE THREAD

**Issue by redclock** [ezibyte/EziSocial-Plugin#2]
After upgrading EziSocial, many UnsupportedOperationException and NullPointerException are reported from our users. Please fix these bugs!

One is:
java.lang.UnsupportedOperationException: Session: an attempt was made to request new permissions for a session that has a pending request.
at com.facebook.Session.requestNewPermissions(Session.java:1006)
at com.facebook.Session.requestNewReadPermissions(Session.java:492)
at com.ezibyte.social.EziSocialManager$12.run(EziSocialManager.java:1516)
at android.os.Handler.handleCallback(Handler.java:730)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:5455)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:525)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1187)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
at dalvik.system.NativeStart.main(Native Method)

The other is:
java.lang.NullPointerException
at com.ezibyte.social.EziSocialManager$5.call(EziSocialManager.java:775)
at com.facebook.Session$3$1.run(Session.java:1302)
at android.os.Handler.handleCallback(Handler.java:615)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:155)
at android.app.ActivityThread.main(ActivityThread.java:5454)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1029)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:796)
at dalvik.system.NativeStart.main(Native Method)

**Comment by ezibyte** [comment]
Fixed in EziSocial version 2.3
